// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 15.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace PUL
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "15.0.26004.1")]
    public partial class UIMap
    {
        
        /// <summary>
        /// AddToCart - Use 'AddToCartParams' to pass parameters into this method.
        /// </summary>
        public void AddToCart()
        {
            #region Variable Declarations
            HtmlDiv uIItemPane = this.UIBingInternetExplorerWindow.UIBingDocument.UISb_formCustom.UIItemPane;
            BrowserWindow uIBingInternetExplorerWindow = this.UIBingInternetExplorerWindow;
            HtmlHyperlink uILightingHyperlink = this.UIBingInternetExplorerWindow.UIHomePagePartsUnlimitDocument.UILightingHyperlink;
            HtmlImage uIHalogenHeadlights2PaImage = this.UIBingInternetExplorerWindow.UIBrowseProductsPartsUDocument.UIHalogenHeadlights2PaImage;
            HtmlHyperlink uIAddtoCartHyperlink = this.UIBingInternetExplorerWindow.UIProductHalogenHeadliDocument.UIStoredetailsPane.UIAddtoCartHyperlink;
            WinCustom uIItemCustom = this.UIItemWindow.UIItemCustom;
            #endregion

            // Go to web page 'http://www.bing.com/' using new browser instance
            this.UIBingInternetExplorerWindow.LaunchUrl(new System.Uri(this.AddToCartParams.UIBingInternetExplorerWindowUrl));

            // Set flag to allow play back to continue if non-essential actions fail. (For example, if a mouse hover action fails.)
            Playback.PlaybackSettings.ContinueOnError = true;

            // Mouse hover  pane at (1, 1)
            Mouse.Hover(uIItemPane, new Point(1, 1));

            // Reset flag to ensure that play back stops if there is an error.
            Playback.PlaybackSettings.ContinueOnError = false;

            // Go to web page 'http://partsunlimitede2edemo.azurewebsites.net/'
            uIBingInternetExplorerWindow.NavigateToUrl(new System.Uri(this.AddToCartParams.UIBingInternetExplorerWindowUrl1));

            // Click 'Lighting' link
            Mouse.Click(uILightingHyperlink, new Point(42, 20));

            // Click 'Halogen Headlights (2 Pack) zoom' image
            Mouse.Click(uIHalogenHeadlights2PaImage, new Point(202, 129));

            // Click 'Add to Cart' link
            Mouse.Click(uIAddtoCartHyperlink, new Point(73, 36));

            // Click custom control
            Mouse.Click(uIItemCustom, new Point(850, -271));
        }
        
        /// <summary>
        /// RecordedMethod1 - Use 'RecordedMethod1Params' to pass parameters into this method.
        /// </summary>
        public void RecordedMethod1()
        {
            #region Variable Declarations
            HtmlHyperlink uIBatteriesHyperlink = this.UIBingInternetExplorerWindow.UIHomePagePartsUnlimitDocument.UIBatteriesHyperlink;
            HtmlImage uIJumperLeadsImage = this.UIBingInternetExplorerWindow.UIBrowseProductsPartsUDocument1.UIJumperLeadsImage;
            HtmlHyperlink uIAddtoCartHyperlink = this.UIBingInternetExplorerWindow.UIProductJumperLeadsPaDocument.UIStoredetailsPane.UIAddtoCartHyperlink;
            BrowserWindow uIBingInternetExplorerWindow = this.UIBingInternetExplorerWindow;
            #endregion

            // Go to web page 'http://partsunlimitede2edemo.azurewebsites.net/' using new browser instance
            this.UIBingInternetExplorerWindow.LaunchUrl(new System.Uri(this.RecordedMethod1Params.UIBingInternetExplorerWindowUrl));

            // Click 'Batteries' link
            Mouse.Click(uIBatteriesHyperlink, new Point(38, 16));

            // Click 'Jumper Leads' image
            Mouse.Click(uIJumperLeadsImage, new Point(108, 250));

            // Click 'Add to Cart' link
            Mouse.Click(uIAddtoCartHyperlink, new Point(102, 18));

            // Perform Close on Browser Window
            uIBingInternetExplorerWindow.Close();
        }
        
        #region Properties
        public virtual AddToCartParams AddToCartParams
        {
            get
            {
                if ((this.mAddToCartParams == null))
                {
                    this.mAddToCartParams = new AddToCartParams();
                }
                return this.mAddToCartParams;
            }
        }
        
        public virtual RecordedMethod1Params RecordedMethod1Params
        {
            get
            {
                if ((this.mRecordedMethod1Params == null))
                {
                    this.mRecordedMethod1Params = new RecordedMethod1Params();
                }
                return this.mRecordedMethod1Params;
            }
        }
        
        public UIBingInternetExplorerWindow UIBingInternetExplorerWindow
        {
            get
            {
                if ((this.mUIBingInternetExplorerWindow == null))
                {
                    this.mUIBingInternetExplorerWindow = new UIBingInternetExplorerWindow();
                }
                return this.mUIBingInternetExplorerWindow;
            }
        }
        
        public UIItemWindow UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow();
                }
                return this.mUIItemWindow;
            }
        }
        #endregion
        
        #region Fields
        private AddToCartParams mAddToCartParams;
        
        private RecordedMethod1Params mRecordedMethod1Params;
        
        private UIBingInternetExplorerWindow mUIBingInternetExplorerWindow;
        
        private UIItemWindow mUIItemWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'AddToCart'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "15.0.26004.1")]
    public class AddToCartParams
    {
        
        #region Fields
        /// <summary>
        /// Go to web page 'http://www.bing.com/' using new browser instance
        /// </summary>
        public string UIBingInternetExplorerWindowUrl = "http://www.bing.com/";
        
        /// <summary>
        /// Go to web page 'http://partsunlimitede2edemo.azurewebsites.net/'
        /// </summary>
        public string UIBingInternetExplorerWindowUrl1 = "http://partsunlimitede2edemo.azurewebsites.net/";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'RecordedMethod1'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "15.0.26004.1")]
    public class RecordedMethod1Params
    {
        
        #region Fields
        /// <summary>
        /// Go to web page 'http://partsunlimitede2edemo.azurewebsites.net/' using new browser instance
        /// </summary>
        public string UIBingInternetExplorerWindowUrl = "http://partsunlimitede2edemo.azurewebsites.net/";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26004.1")]
    public class UIBingInternetExplorerWindow : BrowserWindow
    {
        
        public UIBingInternetExplorerWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "Bing";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("Bing");
            this.WindowTitles.Add("Home Page – Parts Unlimited");
            this.WindowTitles.Add("Browse Products – Parts Unlimited");
            this.WindowTitles.Add("Product - Halogen Headlights (2 Pack) – Parts Unlimited");
            this.WindowTitles.Add("Shopping Cart – Parts Unlimited");
            this.WindowTitles.Add("Product - Jumper Leads – Parts Unlimited");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIBingDocument UIBingDocument
        {
            get
            {
                if ((this.mUIBingDocument == null))
                {
                    this.mUIBingDocument = new UIBingDocument(this);
                }
                return this.mUIBingDocument;
            }
        }
        
        public UIHomePagePartsUnlimitDocument UIHomePagePartsUnlimitDocument
        {
            get
            {
                if ((this.mUIHomePagePartsUnlimitDocument == null))
                {
                    this.mUIHomePagePartsUnlimitDocument = new UIHomePagePartsUnlimitDocument(this);
                }
                return this.mUIHomePagePartsUnlimitDocument;
            }
        }
        
        public UIBrowseProductsPartsUDocument UIBrowseProductsPartsUDocument
        {
            get
            {
                if ((this.mUIBrowseProductsPartsUDocument == null))
                {
                    this.mUIBrowseProductsPartsUDocument = new UIBrowseProductsPartsUDocument(this);
                }
                return this.mUIBrowseProductsPartsUDocument;
            }
        }
        
        public UIProductHalogenHeadliDocument UIProductHalogenHeadliDocument
        {
            get
            {
                if ((this.mUIProductHalogenHeadliDocument == null))
                {
                    this.mUIProductHalogenHeadliDocument = new UIProductHalogenHeadliDocument(this);
                }
                return this.mUIProductHalogenHeadliDocument;
            }
        }
        
        public UIBrowseProductsPartsUDocument1 UIBrowseProductsPartsUDocument1
        {
            get
            {
                if ((this.mUIBrowseProductsPartsUDocument1 == null))
                {
                    this.mUIBrowseProductsPartsUDocument1 = new UIBrowseProductsPartsUDocument1(this);
                }
                return this.mUIBrowseProductsPartsUDocument1;
            }
        }
        
        public UIProductJumperLeadsPaDocument UIProductJumperLeadsPaDocument
        {
            get
            {
                if ((this.mUIProductJumperLeadsPaDocument == null))
                {
                    this.mUIProductJumperLeadsPaDocument = new UIProductJumperLeadsPaDocument(this);
                }
                return this.mUIProductJumperLeadsPaDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIBingDocument mUIBingDocument;
        
        private UIHomePagePartsUnlimitDocument mUIHomePagePartsUnlimitDocument;
        
        private UIBrowseProductsPartsUDocument mUIBrowseProductsPartsUDocument;
        
        private UIProductHalogenHeadliDocument mUIProductHalogenHeadliDocument;
        
        private UIBrowseProductsPartsUDocument1 mUIBrowseProductsPartsUDocument1;
        
        private UIProductJumperLeadsPaDocument mUIProductJumperLeadsPaDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26004.1")]
    public class UIBingDocument : HtmlDocument
    {
        
        public UIBingDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Bing";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://www.bing.com/";
            this.WindowTitles.Add("Bing");
            #endregion
        }
        
        #region Properties
        public UISb_formCustom UISb_formCustom
        {
            get
            {
                if ((this.mUISb_formCustom == null))
                {
                    this.mUISb_formCustom = new UISb_formCustom(this);
                }
                return this.mUISb_formCustom;
            }
        }
        #endregion
        
        #region Fields
        private UISb_formCustom mUISb_formCustom;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26004.1")]
    public class UISb_formCustom : HtmlCustom
    {
        
        public UISb_formCustom(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties["TagName"] = "FORM";
            this.SearchProperties["Id"] = "sb_form";
            this.SearchProperties[UITestControl.PropertyNames.Name] = null;
            this.FilterProperties["Class"] = "sw_box";
            this.FilterProperties["ControlDefinition"] = "class=\"sw_box\" id=\"sb_form\" onsubmit=\"va";
            this.FilterProperties["TagInstance"] = "1";
            this.WindowTitles.Add("Bing");
            #endregion
        }
        
        #region Properties
        public HtmlDiv UIItemPane
        {
            get
            {
                if ((this.mUIItemPane == null))
                {
                    this.mUIItemPane = new HtmlDiv(this);
                    #region Search Criteria
                    this.mUIItemPane.SearchProperties[HtmlDiv.PropertyNames.Id] = null;
                    this.mUIItemPane.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUIItemPane.FilterProperties[HtmlDiv.PropertyNames.InnerText] = null;
                    this.mUIItemPane.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUIItemPane.FilterProperties[HtmlDiv.PropertyNames.Class] = "b_searchboxForm";
                    this.mUIItemPane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"b_searchboxForm\" role=\"search\" data-bm=\"17\"";
                    this.mUIItemPane.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "8";
                    this.mUIItemPane.WindowTitles.Add("Bing");
                    #endregion
                }
                return this.mUIItemPane;
            }
        }
        #endregion
        
        #region Fields
        private HtmlDiv mUIItemPane;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26004.1")]
    public class UIHomePagePartsUnlimitDocument : HtmlDocument
    {
        
        public UIHomePagePartsUnlimitDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Home Page – Parts Unlimited";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://partsunlimitede2edemo.azurewebsites.net/";
            this.WindowTitles.Add("Home Page – Parts Unlimited");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink UILightingHyperlink
        {
            get
            {
                if ((this.mUILightingHyperlink == null))
                {
                    this.mUILightingHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUILightingHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUILightingHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUILightingHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUILightingHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Lighting";
                    this.mUILightingHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/Store/Browse";
                    this.mUILightingHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUILightingHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://partsunlimitede2edemo.azurewebsites.net/Store/Browse?CategoryId=2";
                    this.mUILightingHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = null;
                    this.mUILightingHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "href=\"/Store/Browse?CategoryId=2\"";
                    this.mUILightingHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "15";
                    this.mUILightingHyperlink.WindowTitles.Add("Home Page – Parts Unlimited");
                    #endregion
                }
                return this.mUILightingHyperlink;
            }
        }
        
        public HtmlHyperlink UIBatteriesHyperlink
        {
            get
            {
                if ((this.mUIBatteriesHyperlink == null))
                {
                    this.mUIBatteriesHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIBatteriesHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUIBatteriesHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIBatteriesHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIBatteriesHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Batteries";
                    this.mUIBatteriesHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/Store/Browse";
                    this.mUIBatteriesHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUIBatteriesHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://partsunlimitede2edemo.azurewebsites.net/Store/Browse?CategoryId=4";
                    this.mUIBatteriesHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = null;
                    this.mUIBatteriesHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "href=\"/Store/Browse?CategoryId=4\"";
                    this.mUIBatteriesHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "17";
                    this.mUIBatteriesHyperlink.WindowTitles.Add("Home Page – Parts Unlimited");
                    #endregion
                }
                return this.mUIBatteriesHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mUILightingHyperlink;
        
        private HtmlHyperlink mUIBatteriesHyperlink;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26004.1")]
    public class UIBrowseProductsPartsUDocument : HtmlDocument
    {
        
        public UIBrowseProductsPartsUDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Browse Products – Parts Unlimited";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/Store/Browse";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://partsunlimitede2edemo.azurewebsites.net/Store/Browse?CategoryId=2";
            this.WindowTitles.Add("Browse Products – Parts Unlimited");
            #endregion
        }
        
        #region Properties
        public HtmlImage UIHalogenHeadlights2PaImage
        {
            get
            {
                if ((this.mUIHalogenHeadlights2PaImage == null))
                {
                    this.mUIHalogenHeadlights2PaImage = new HtmlImage(this);
                    #region Search Criteria
                    this.mUIHalogenHeadlights2PaImage.SearchProperties[HtmlImage.PropertyNames.Id] = null;
                    this.mUIHalogenHeadlights2PaImage.SearchProperties[HtmlImage.PropertyNames.Name] = null;
                    this.mUIHalogenHeadlights2PaImage.SearchProperties[HtmlImage.PropertyNames.Alt] = "Halogen Headlights (2 Pack) zoom";
                    this.mUIHalogenHeadlights2PaImage.FilterProperties[HtmlImage.PropertyNames.AbsolutePath] = "/images/product_lighting_headlight.jpg";
                    this.mUIHalogenHeadlights2PaImage.FilterProperties[HtmlImage.PropertyNames.Src] = "http://partsunlimitede2edemo.azurewebsites.net/images/product_lighting_headlight." +
                        "jpg";
                    this.mUIHalogenHeadlights2PaImage.FilterProperties[HtmlImage.PropertyNames.LinkAbsolutePath] = "/Store/Details/1";
                    this.mUIHalogenHeadlights2PaImage.FilterProperties[HtmlImage.PropertyNames.Href] = "http://partsunlimitede2edemo.azurewebsites.net/Store/Details/1";
                    this.mUIHalogenHeadlights2PaImage.FilterProperties[HtmlImage.PropertyNames.Class] = null;
                    this.mUIHalogenHeadlights2PaImage.FilterProperties[HtmlImage.PropertyNames.ControlDefinition] = "alt=\"Halogen Headlights (2 Pack) zoom\" s";
                    this.mUIHalogenHeadlights2PaImage.FilterProperties[HtmlImage.PropertyNames.TagInstance] = "3";
                    this.mUIHalogenHeadlights2PaImage.WindowTitles.Add("Browse Products – Parts Unlimited");
                    #endregion
                }
                return this.mUIHalogenHeadlights2PaImage;
            }
        }
        #endregion
        
        #region Fields
        private HtmlImage mUIHalogenHeadlights2PaImage;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26004.1")]
    public class UIProductHalogenHeadliDocument : HtmlDocument
    {
        
        public UIProductHalogenHeadliDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Product - Halogen Headlights (2 Pack) – Parts Unlimited";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/Store/Details/1";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://partsunlimitede2edemo.azurewebsites.net/Store/Details/1";
            this.WindowTitles.Add("Product - Halogen Headlights (2 Pack) – Parts Unlimited");
            #endregion
        }
        
        #region Properties
        public UIStoredetailsPane UIStoredetailsPane
        {
            get
            {
                if ((this.mUIStoredetailsPane == null))
                {
                    this.mUIStoredetailsPane = new UIStoredetailsPane(this);
                }
                return this.mUIStoredetailsPane;
            }
        }
        #endregion
        
        #region Fields
        private UIStoredetailsPane mUIStoredetailsPane;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26004.1")]
    public class UIStoredetailsPane : HtmlDiv
    {
        
        public UIStoredetailsPane(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDiv.PropertyNames.Id] = "store-details";
            this.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Halogen Headlights (2 Pack)\r\n\r\n\r\n\r\n\r\n \r\n";
            this.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.Class] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "id=\"store-details\"";
            this.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "18";
            this.WindowTitles.Add("Product - Halogen Headlights (2 Pack) – Parts Unlimited");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink UIAddtoCartHyperlink
        {
            get
            {
                if ((this.mUIAddtoCartHyperlink == null))
                {
                    this.mUIAddtoCartHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIAddtoCartHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUIAddtoCartHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIAddtoCartHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIAddtoCartHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Add to Cart";
                    this.mUIAddtoCartHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/ShoppingCart/AddToCart/1";
                    this.mUIAddtoCartHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUIAddtoCartHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://partsunlimitede2edemo.azurewebsites.net/ShoppingCart/AddToCart/1";
                    this.mUIAddtoCartHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = "btn";
                    this.mUIAddtoCartHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "class=\"btn\" href=\"/ShoppingCart/AddToCar";
                    this.mUIAddtoCartHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "1";
                    this.mUIAddtoCartHyperlink.WindowTitles.Add("Product - Halogen Headlights (2 Pack) – Parts Unlimited");
                    #endregion
                }
                return this.mUIAddtoCartHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mUIAddtoCartHyperlink;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26004.1")]
    public class UIBrowseProductsPartsUDocument1 : HtmlDocument
    {
        
        public UIBrowseProductsPartsUDocument1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Browse Products – Parts Unlimited";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/Store/Browse";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://partsunlimitede2edemo.azurewebsites.net/Store/Browse?CategoryId=4";
            this.WindowTitles.Add("Browse Products – Parts Unlimited");
            #endregion
        }
        
        #region Properties
        public HtmlImage UIJumperLeadsImage
        {
            get
            {
                if ((this.mUIJumperLeadsImage == null))
                {
                    this.mUIJumperLeadsImage = new HtmlImage(this);
                    #region Search Criteria
                    this.mUIJumperLeadsImage.SearchProperties[HtmlImage.PropertyNames.Id] = null;
                    this.mUIJumperLeadsImage.SearchProperties[HtmlImage.PropertyNames.Name] = null;
                    this.mUIJumperLeadsImage.SearchProperties[HtmlImage.PropertyNames.Alt] = "Jumper Leads";
                    this.mUIJumperLeadsImage.FilterProperties[HtmlImage.PropertyNames.AbsolutePath] = "/images/product_batteries_jumper-leads.jpg";
                    this.mUIJumperLeadsImage.FilterProperties[HtmlImage.PropertyNames.Src] = "http://partsunlimitede2edemo.azurewebsites.net/images/product_batteries_jumper-le" +
                        "ads.jpg";
                    this.mUIJumperLeadsImage.FilterProperties[HtmlImage.PropertyNames.LinkAbsolutePath] = "/Store/Details/15";
                    this.mUIJumperLeadsImage.FilterProperties[HtmlImage.PropertyNames.Href] = "http://partsunlimitede2edemo.azurewebsites.net/Store/Details/15";
                    this.mUIJumperLeadsImage.FilterProperties[HtmlImage.PropertyNames.Class] = null;
                    this.mUIJumperLeadsImage.FilterProperties[HtmlImage.PropertyNames.ControlDefinition] = "alt=\"Jumper Leads\" src=\"/images/product_";
                    this.mUIJumperLeadsImage.FilterProperties[HtmlImage.PropertyNames.TagInstance] = "8";
                    this.mUIJumperLeadsImage.WindowTitles.Add("Browse Products – Parts Unlimited");
                    #endregion
                }
                return this.mUIJumperLeadsImage;
            }
        }
        #endregion
        
        #region Fields
        private HtmlImage mUIJumperLeadsImage;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26004.1")]
    public class UIProductJumperLeadsPaDocument : HtmlDocument
    {
        
        public UIProductJumperLeadsPaDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Product - Jumper Leads – Parts Unlimited";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/Store/Details/15";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://partsunlimitede2edemo.azurewebsites.net/Store/Details/15";
            this.WindowTitles.Add("Product - Jumper Leads – Parts Unlimited");
            #endregion
        }
        
        #region Properties
        public UIStoredetailsPane1 UIStoredetailsPane
        {
            get
            {
                if ((this.mUIStoredetailsPane == null))
                {
                    this.mUIStoredetailsPane = new UIStoredetailsPane1(this);
                }
                return this.mUIStoredetailsPane;
            }
        }
        #endregion
        
        #region Fields
        private UIStoredetailsPane1 mUIStoredetailsPane;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26004.1")]
    public class UIStoredetailsPane1 : HtmlDiv
    {
        
        public UIStoredetailsPane1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDiv.PropertyNames.Id] = "store-details";
            this.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Jumper Leads\r\n\r\n\r\n\r\n\r\n \r\n \r\n\r\n\r\nUSD $16.";
            this.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.Class] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "id=\"store-details\"";
            this.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "18";
            this.WindowTitles.Add("Product - Jumper Leads – Parts Unlimited");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink UIAddtoCartHyperlink
        {
            get
            {
                if ((this.mUIAddtoCartHyperlink == null))
                {
                    this.mUIAddtoCartHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIAddtoCartHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUIAddtoCartHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIAddtoCartHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIAddtoCartHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Add to Cart";
                    this.mUIAddtoCartHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/ShoppingCart/AddToCart/15";
                    this.mUIAddtoCartHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUIAddtoCartHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://partsunlimitede2edemo.azurewebsites.net/ShoppingCart/AddToCart/15";
                    this.mUIAddtoCartHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = "btn";
                    this.mUIAddtoCartHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "class=\"btn\" href=\"/ShoppingCart/AddToCar";
                    this.mUIAddtoCartHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "1";
                    this.mUIAddtoCartHyperlink.WindowTitles.Add("Product - Jumper Leads – Parts Unlimited");
                    #endregion
                }
                return this.mUIAddtoCartHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mUIAddtoCartHyperlink;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26004.1")]
    public class UIItemWindow : WinWindow
    {
        
        public UIItemWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.AccessibleName] = "Desktop";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "#32769";
            #endregion
        }
        
        #region Properties
        public WinCustom UIItemCustom
        {
            get
            {
                if ((this.mUIItemCustom == null))
                {
                    this.mUIItemCustom = new WinCustom(this);
                }
                return this.mUIItemCustom;
            }
        }
        #endregion
        
        #region Fields
        private WinCustom mUIItemCustom;
        #endregion
    }
}
